name: Build JavaFX App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven (includes jlink)
        run: mvn clean package

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: MyJavaFXApp
      #     path: target/*.jar
