name: Build JavaFX App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JavaFX jmods
        run: |
          curl -L -o openjfx.zip https://download2.gluonhq.com/openjfx/21.0.3/openjfx-21.0.3_linux-x64_bin-jmods.zip
          unzip openjfx.zip -d javafx-jmods

      - name: Create runtime image
        run: |
          jlink \
            --module-path "$JAVA_HOME/jmods:javafx-jmods/javafx-jmods-21.0.3" \
            --add-modules javafx.controls,javafx.fxml,java.sql \
            --output runtime    

      - name: Build with Maven
        run: mvn clean package
